import Head from "next/head";
import Link from "next/link";

export default function About() {
  return (
    <div>
      <Head>
        <title>ICT School</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <Link href="/">To Home page</Link>
      </main>
    </div>
  );
}
